-- hospitals

DROP TABLE cleaned_hospitals;
CREATE TABLE cleaned_hospitals 
ROW FORMAT DELIMITED
-- ROW FORMAT DELIMITED 
AS SELECT 
CAST(PROVIDER_ID AS INT), 
HOSPITAL_NAME, 
CITY, 
STATE, 
HOSPITAL_TYPE,
HOSPITAL_OWNERSHIP
FROM hospitals;

-- effective_care

DROP TABLE cleaned_effective_care;
CREATE TABLE cleaned_effective_care
ROW FORMAT DELIMITED
AS SELECT 
CAST(PROVIDER_ID AS INT), 
STATE
CONDITION, 
MEASURE_ID, 
MEASURE_NAME, 
CAST(SCORE AS INT), 
FROM effective_care;

-- effective_care_state

DROP TABLE cleaned_effective_care_state;
CREATE TABLE cleaned_effective_care_state
ROW FORMAT DELIMITED
AS SELECT 
CAST(PROVIDER_ID AS INT), 
STATE,
CONDITION, 
MEASURE_ID, 
MEASURE_NAME, 
CAST(SCORE AS INT)
FROM effective_care;

-- readmissions

DROP TABLE cleaned_readmissions;
CREATE TABLE cleaned_readmissions
ROW FORMAT DELIMITED
AS SELECT
CAST(PROVIDER_ID AS INT),
MEASURE_ID,
CAST(SCORE AS INT),
LOWER_ESTIMATE,
HIGHER_ESTIMATE,
FROM readmissions;

-- hcahps

DROP TABLE cleaned_hcahps;
CREATE TABLE cleaned_hcahps
ROW FORMAT DELIMITED
AS SELECT
CAST(PROVIDER_ID AS INT),
HOSPITAL_NAME,
HCAHPS_MEASURE_ID,
HCAHPS_QUESTION,
CAST(HCAHPS_LINEAR_MEAN_VALUE AS INT)
FROM hcahps;
